.\" Generated with help2man.
.TH EDITORCONFIG-CTEST "1" "May 2020" "editorconfig-ctest version 1" "User Commands"
.SH NAME
editorconfig-ctest \- conformance test for editorconfig
.SH DESCRIPTION
.SS "Usage"
editorconfig\-ctest [\-h] [\-d DIR] [\-f FILE] [\-\-exit\-zero] [\-\-verbose]
.SS "Optional arguments"
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-d\fR DIR, \fB\-\-dir\fR DIR
test directory
.TP
\fB\-f\fR FILE, \fB\-\-file\fR FILE
test file
.TP
\fB\-\-exit\-zero\fR
always exit with status code zero
.TP
\fB\-\-verbose\fR
show verbose output
.TP
\fB\-\-version\fR
show program's version number and exit
.SH "SEE ALSO"
editorconfig(1)
